---
title: "Distances_genomes"
format:
  gfm:
    toc: true
    code-tools: true
    fig-dir: "figs"
execute:
  echo: true
editor: visual
---

```{r}
# Install packages once if needed:
# install.packages(c("ape", "ggplot2", "ggrepel"))

library(ape)
library(ggplot2)
library(ggrepel)
```

## Plot distances

```{r plot-pcoa,  fig.width=12, fig.height=12, fig.align='center'}

# 1. Read the distance matrix
dist_mat <- read.table(
  "data/bnaipus16_distances.tab",
  header = TRUE,
  row.names = 1,
  check.names = FALSE
)

labs <- read.table("data/Varieties_bnapus.csv", 
                  header = TRUE,
                  check.names = FALSE,
                  sep = ','
)

# 2. Make sure column names match row names (same order)
colnames(dist_mat) <- rownames(dist_mat)

# OPTIONAL: check it’s symmetric
all(rownames(dist_mat) == colnames(dist_mat))

# 3. Run PCoA (ape::pcoa)
dist_obj <- as.dist(dist_mat)
pcoa_res <- pcoa(dist_obj)

# 4. Build a data frame for plotting
pcoa_df <- as.data.frame(pcoa_res$vectors[, 1:2])
pcoa_df$variety <- rownames(pcoa_df)

pcoa_df <- merge(pcoa_df, labs, by.x = "variety", by.y = "var")

scale_fill_manual(values = c(
  "#E69F00", "#56B4E9", "#009E73", "#0072B2"
))

# 5. Plot with ggplot
ggplot(pcoa_df, aes(x = Axis.1, y = Axis.2, label = variety, fill = origin)) +
  
  # Draw large filled points with outline
  geom_point(size = 10, shape = 21, color = "black", alpha = 0.6) +
  
  geom_text_repel(
    size = 6, 
    fontface = "bold",
    box.padding = 1.0,
    point.padding = 0.8,
    min.segment.length = 0,
    max.overlaps = Inf
  ) +

  theme_minimal(base_size = 20) +
  scale_fill_manual(values = c(
  "#E69F00", "#56B4E9", "#009E73", "#0072B2")) +
  theme(
    axis.title = element_text(size = 24, face = "bold"),
    axis.text = element_text(size = 20),
    plot.title = element_text(size = 26, face = "bold", hjust = 0.5)
  ) +
  labs(
    x = "PCoA 1",
    y = "PCoA 2",
    title = bquote(italic(B.~napus) ~ "reference varieties")
  )
# 6. Save the plot to a file (so you can open it)
#ggsave("bnapus_pcoa.png", plot = p, width = 6, height = 5, dpi = 300)

```
